-- Story 1.2 -- Gate de Whitelist de Invitación (AD-5).
--
-- Dos tablas separadas, cada una con su propia PK y su propia columna de
-- AniList id -- nunca conflar el id de AniList de la whitelist con el de
-- app_user, aunque ambos apunten a la misma cuenta remota.
--
-- El UNIQUE en anilist_user_id de app_user es la red de seguridad contra la
-- carrera de doble creación en el primer login concurrente: dos requests
-- concurrentes que ambos pasan el gate de whitelist para el mismo usuario
-- solo logran insertar una fila; el segundo INSERT falla con una violación
-- de constraint que la capa de aplicación resuelve releyendo la fila ya
-- insertada (ver auth.AppUserProvisioningService). UNIQUE en Postgres crea
-- su propio índice btree, así que no hace falta un índice adicional.

CREATE TABLE whitelisted_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anilist_user_id BIGINT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_whitelisted_user_anilist_user_id UNIQUE (anilist_user_id)
);

CREATE TABLE app_user (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anilist_user_id   BIGINT NOT NULL,
    theme_preference  VARCHAR(20) NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_app_user_anilist_user_id UNIQUE (anilist_user_id)
);
