-- Story 2.1 -- Sincronización forzada en el login.
--
-- tracking_entry mantiene su propia PK más una columna indexada separada
-- para el id remoto de AniList (anilist_media_id) -- nunca conflar ambos ids
-- (mismo criterio que app_user.anilist_user_id en V1).
--
-- El UNIQUE (app_user_id, anilist_media_id) es la base de la reconciliación
-- completa por corrida en sync.SyncService: upsert in-place si la fila ya
-- existe (aunque estuviera dada de baja lógica), insert si es la primera vez
-- que aparece ese anime para ese usuario. Un índice adicional sobre
-- anilist_media_id a secas (no cubierto por ese UNIQUE compuesto, que solo
-- sirve para lookups que empiezan por app_user_id) soporta consultas futuras
-- por anime sin importar el usuario.
--
-- snapshot es un registro histórico e inmutable por (tracking_entry, corrida)
-- -- nunca un agregado único por usuario -- con su propio taken_at, así que
-- no lleva ningún UNIQUE: la misma corrida no vuelve a escribir dos veces
-- para la misma tracking_entry, pero eso lo garantiza sync.SyncService, no el
-- esquema.

CREATE TABLE tracking_entry (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id       BIGINT NOT NULL REFERENCES app_user(id),
    anilist_media_id  BIGINT NOT NULL,
    status            VARCHAR(20) NOT NULL,
    last_episode      INTEGER NOT NULL,
    active            BOOLEAN NOT NULL,
    CONSTRAINT uq_tracking_entry_app_user_anilist_media UNIQUE (app_user_id, anilist_media_id)
);

CREATE INDEX idx_tracking_entry_anilist_media_id ON tracking_entry (anilist_media_id);

CREATE TABLE snapshot (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_entry_id  BIGINT NOT NULL REFERENCES tracking_entry(id),
    episode_progress   INTEGER NOT NULL,
    taken_at           TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_snapshot_tracking_entry_id ON snapshot (tracking_entry_id);
